"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import offerhospitalityresponsewrapper as shared_offerhospitalityresponsewrapper
from ...models.shared import offerquerybuildfromcatalogofferingshospitalitywrapper as shared_offerquerybuildfromcatalogofferingshospitalitywrapper
from typing import Optional


@dataclasses.dataclass
class BuildFromCatalogOfferingsRequest:
    offer_query_build_from_catalog_offerings_hospitality_wrapper: shared_offerquerybuildfromcatalogofferingshospitalitywrapper.OfferQueryBuildFromCatalogOfferingsHospitalityWrapper = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    trace_id: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'TraceId', 'style': 'simple', 'explode': False }})
    r"""Identifier used to correlate API invocations across long-running or multi-call business flows."""
    travelport_plus_session_id: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'TravelportPlusSessionID', 'style': 'simple', 'explode': False }})
    r"""Travelport Plus Session ID used to maintain an established agency session"""
    xauth_travelport_accessgroup: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'XAUTH_TRAVELPORT_ACCESSGROUP', 'style': 'simple', 'explode': False }})
    r"""Identifies the Travelport access group with which the caller is associated"""
    



@dataclasses.dataclass
class BuildFromCatalogOfferingsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    offer_hospitality_response_wrapper: Optional[shared_offerhospitalityresponsewrapper.OfferHospitalityResponseWrapper] = dataclasses.field(default=None)
    r"""Created - 201"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

