"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import imagesizeenum as shared_imagesizeenum
from ..shared import propertiesresponsewrapper as shared_propertiesresponsewrapper
from typing import Optional


@dataclasses.dataclass
class GetPropertiesDetailRequest:
    chain_code: str = dataclasses.field(metadata={'query_param': { 'field_name': 'chainCode', 'style': 'form', 'explode': True }})
    r"""Hotel chain code"""
    property_code: str = dataclasses.field(metadata={'query_param': { 'field_name': 'propertyCode', 'style': 'form', 'explode': True }})
    r"""Property code"""
    image_size: Optional[shared_imagesizeenum.ImageSizeEnum] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'ImageSize', 'style': 'form', 'explode': True }})
    r"""The size of the image to be returned"""
    trace_id: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'TraceId', 'style': 'simple', 'explode': False }})
    r"""Identifier used to correlate API invocations across long-running or multi-call business flows."""
    xauth_travelport_accessgroup: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'XAUTH_TRAVELPORT_ACCESSGROUP', 'style': 'simple', 'explode': False }})
    r"""Identifies the Travelport access group with which the caller is associated"""
    



@dataclasses.dataclass
class GetPropertiesDetailResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    properties_response_wrapper: Optional[shared_propertiesresponsewrapper.PropertiesResponseWrapper] = dataclasses.field(default=None)
    r"""OK - Successful Response - 200"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

