"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AvailabilityStatusEnum(str, Enum):
    r"""Identifies the availability status of an item."""
    OPEN = 'Open'
    CLOSE = 'Close'
    CLOSED_ON_ARRIVAL = 'ClosedOnArrival'
    CLOSED_ON_ARRIVAL_ON_REQUEST = 'ClosedOnArrivalOnRequest'
    ON_REQUEST = 'OnRequest'
    REMOVE_CLOSE_ONLY = 'RemoveCloseOnly'
    OTHER = 'Other'
