"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CabinAirEnum(str, Enum):
    r"""Specifies the cabin type (e.g. first, business, economy)."""
    PREMIUM_FIRST = 'PremiumFirst'
    FIRST = 'First'
    BUSINESS = 'Business'
    PREMIUM_ECONOMY = 'PremiumEconomy'
    ECONOMY = 'Economy'
