"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .catalogofferingsrequesthospitality import CatalogOfferingsRequestHospitality
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CatalogOfferingsQueryRequest:
    at_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('@type') }})
    catalog_offerings_request: List[CatalogOfferingsRequestHospitality] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('CatalogOfferingsRequest') }})
    

