"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ChangeFeeMethodEnumBase(str, Enum):
    EMD = 'EMD'
    MCO = 'MCO'
    TAX = 'Tax'
    UNKNOWN = 'Unknown'
