"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CommissionEnum(str, Enum):
    r"""Type of commission"""
    FULL = 'Full'
    PARTIAL = 'Partial'
    NON_PAYING = 'Non-paying'
    NO_SHOW = 'No-show'
    ADJUSTMENT = 'Adjustment'
    COMMISSIONABLE = 'Commissionable'
