"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .commission import Commission
from .commissionapplyenum import CommissionApplyEnum
from .traveleridentifierref import TravelerIdentifierRef
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Commissions:
    commission: Commission = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Commission') }})
    at_type: Optional[str] = dataclasses.field(default='Commissions', metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('@type'), 'exclude': lambda f: f is None }})
    apply_to: Optional[CommissionApplyEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ApplyTo'), 'exclude': lambda f: f is None }})
    traveler_identifier_ref: Optional[List[TravelerIdentifierRef]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('TravelerIdentifierRef'), 'exclude': lambda f: f is None }})
    

