"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CommentSourceEnum(str, Enum):
    AGENCY = 'Agency'
    SUPPLIER = 'Supplier'
    TRAVELER = 'Traveler'
