"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CurrencySourceEnum(str, Enum):
    r"""The system requesting or returning the currency code specified in the attribute"""
    SUPPLIER = 'Supplier'
    CHARGED = 'Charged'
    REQUESTED = 'Requested'
