"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CurrencyCode:
    r"""Currency codes are the three-letter alphabetic codes that represent the various currencies used throughout the world."""
    code_authority: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('codeAuthority'), 'exclude': lambda f: f is None }})
    r"""Currency code authority"""
    decimal_authority: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('decimalAuthority'), 'exclude': lambda f: f is None }})
    r"""Currency code decimal authority"""
    decimal_place: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('decimalPlace'), 'exclude': lambda f: f is None }})
    r"""Currency code decimal place"""
    value: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('value'), 'exclude': lambda f: f is None }})
    

