"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .customerloyalty import CustomerLoyalty
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CustomerLoyaltyCredit:
    customer_loyalty: CustomerLoyalty = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('CustomerLoyalty') }})
    r"""Specifies the ID for the membership program."""
    earned: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Earned') }})
    r"""Represents the amount of award credit awarded for this offer\/offering. Award credit can be used for purchasing goods and services through a customer loyalty program"""
    status: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Status') }})
    r"""Represents the amount of status credit awarded for this offer\/offering. Status credit allow a customer to move up the ladder of a customer loyalty program"""
    at_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('@type'), 'exclude': lambda f: f is None }})
    

