"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class DocumentTypeEnum(str, Enum):
    r"""Document type like EMD, MCO"""
    EMD = 'EMD'
    MCO = 'MCO'
    TICKET = 'Ticket'
