"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class EnumTelephoneRole(str, Enum):
    MOBILE = 'Mobile'
    HOME = 'Home'
    WORK = 'Work'
    OFFICE = 'Office'
    FAX = 'Fax'
    OTHER = 'Other'
