"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class FareQualifierENUMBase(str, Enum):
    CONSOLIDATOR = 'Consolidator'
    GOVERNMENT = 'Government'
    MARINE = 'Marine'
    MILITARY = 'Military'
    REWARD = 'Reward'
    STAND_BY = 'StandBy'
    STAFF = 'Staff'
    STUDENT = 'Student'
    TOUR = 'Tour'
    YOUTH = 'Youth'
    VIST_FRIENDS_AND_RELATIVES = 'VistFriendsAndRelatives'
