"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class GenderEnum(str, Enum):
    r"""Gender Type Male, Female etc. This field is not used by Hotel APIs and will be ignored"""
    MALE = 'Male'
    FEMALE = 'Female'
    UNKNOWN = 'Unknown'
    UNDISCLOSED = 'Undisclosed'
