"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class HotelAggregatorEnum(str, Enum):
    TRAVELPORT = 'Travelport'
    AGODA = 'Agoda'
    BOOKING = 'Booking'
    EXPEDIA = 'Expedia'
    BONOTEL = 'Bonotel'
