"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class HotelSortOrderEnum(str, Enum):
    r"""The method to be used in sorting hotel properties"""
    STAR_RATING = 'StarRating'
    PROXIMITY = 'Proximity'
