"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class IdentifierTypeENUM(str, Enum):
    RESERVATION = 'Reservation'
    LOCATOR = 'Locator'
    SUPPLIER_LOCATOR = 'SupplierLocator'
    DOCUMENT_NUMBER = 'DocumentNumber'
