"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ImageSizeEnum(str, Enum):
    r"""Indicates the size of the image. Hospitality APIs no longer support thumbnail"""
    LARGE = 'Large'
    MEDIUM = 'Medium'
    SMALL = 'Small'
    THUMBNAIL = 'Thumbnail'
    EXTRA_LARGE = 'ExtraLarge'
