"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MeasurementTypeEnum(str, Enum):
    r"""The type of measurement such as width, height, weight"""
    WIDTH = 'Width'
    HEIGHT = 'Height'
    DEPTH = 'Depth'
    WEIGHT = 'Weight'
    OVERALL_DIMENSION = 'OverallDimension'
