"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .nextstep import NextStep
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class NextSteps:
    next_step: List[NextStep] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('NextStep') }})
    base_uri: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('baseURI') }})
    r"""The base portion of the uri in order to shorten the uri's in the individual steps"""
    id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id'), 'exclude': lambda f: f is None }})
    r"""Optional internally referenced id"""
    

