"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .identifier import Identifier
from .price import Price
from .productid import ProductID
from .termsandconditionsfull import TermsAndConditionsFull
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Offer:
    at_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('@type') }})
    price: Price = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Price') }})
    product: List[ProductID] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Product') }})
    terms_and_conditions_full: List[TermsAndConditionsFull] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('TermsAndConditionsFull') }})
    identifier: Optional[Identifier] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Identifier'), 'exclude': lambda f: f is None }})
    r"""Identifier provides the ability to create a globally unique identifier. For the identifier to be globally unique it must have a system provided identifier and the system must be identified using a global naming authority. System identification uses the domain naming system (DNS) to assure they are globally unique and should be an URL. The system provided ID will typically be a primary or surrogate key in a database."""
    id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id'), 'exclude': lambda f: f is None }})
    r"""Local indentifier within a given message for this object."""
    offer_ref: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offerRef'), 'exclude': lambda f: f is None }})
    r"""Used to reference another instance of this object in the same message"""
    parent_offer_ref: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('parentOfferRef'), 'exclude': lambda f: f is None }})
    r"""A reference to the Offer this offer is sold in conjunction with"""
    passive_offer_ind: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('passiveOfferInd'), 'exclude': lambda f: f is None }})
    r"""If true, the Offer is passive for booking purposes."""
    

