"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .buildfromcatalogofferinghospitality import BuildFromCatalogOfferingHospitality
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OfferQueryBuildFromCatalogOffering:
    at_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('@type') }})
    build_from_catalog_offering_hospitality: Optional[BuildFromCatalogOfferingHospitality] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('BuildFromCatalogOfferingHospitality'), 'exclude': lambda f: f is None }})
    

