"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OperationalStatusENUMBase(str, Enum):
    FLIGHT_BOARDING = 'FlightBoarding'
    FLIGHT_CANCELLED = 'FlightCancelled'
    FLIGHT_DEPARTED = 'FlightDeparted'
    FLIGHT_PAST_SCHEDULED_DEPARTURE = 'FlightPastScheduledDeparture'
    NOT_AVAILABLE_USE_SEARCH = 'NotAvailableUseSearch'
