"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OptInStatusEnum(str, Enum):
    r"""Used to indicate marketing preferences, OptIn, OptOut"""
    OPTED_IN = 'OptedIn'
    OPTED_OUT = 'OptedOut'
    UNKNOWN = 'Unknown'
