"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import texttitleanddescription as shared_texttitleanddescription
from ..shared import yesnounknownenum as shared_yesnounknownenum
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PetPolicy:
    allowed: shared_yesnounknownenum.YesNoUnknownEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('allowed') }})
    r"""Yes , No , Unknown"""
    at_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('@type'), 'exclude': lambda f: f is None }})
    description: Optional[shared_texttitleanddescription.TextTitleAndDescription] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Description'), 'exclude': lambda f: f is None }})
    r"""Descriptive text"""
    policy_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('policyCode'), 'exclude': lambda f: f is None }})
    r"""Pet policy code"""
    

