"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class PositionAccuracyEnum(str, Enum):
    r"""Specifies the level of accuracy for the position"""
    ZIP9_CODE = 'Zip9Code'
    ZIP7_CODE = 'Zip7Code'
    ZIP5_CODE = 'Zip5Code'
    STREET = 'Street'
    STATE = 'State'
    PROPERTY = 'Property'
    INTERSECTION = 'Intersection'
    EXACT = 'Exact'
    COUNTY = 'County'
    CITY = 'City'
    BLOCK = 'Block'
