"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import propertiesqueryprecisionsearch as shared_propertiesqueryprecisionsearch
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PropertiesQueryPrecisionSearchWrapper:
    properties_query_search: Optional[shared_propertiesqueryprecisionsearch.PropertiesQueryPrecisionSearch] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('PropertiesQuerySearch'), 'exclude': lambda f: f is None }})
    

