"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class PurposeEnum(str, Enum):
    BUSINESS = 'Business'
    PLEASURE = 'Pleasure'
    CHARTER_SERVICE = 'Charter Service'
