"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class RailDiscountCard:
    r"""The name of the Rail Discount"""
    supplier_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('supplierCode') }})
    r"""Code of the Supplier"""
    reference_number: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('referenceNumber'), 'exclude': lambda f: f is None }})
    r"""ReferenceNumber"""
    value: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('value'), 'exclude': lambda f: f is None }})
    

