"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ResultStatusEnum(str, Enum):
    r"""The status of an error or warning"""
    NOT_PROCESSED = 'Not processed'
    INCOMPLETE = 'Incomplete'
    COMPLETE = 'Complete'
    UNKNOWN = 'Unknown'
