"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .roomstaycandidate import RoomStayCandidate
from akaris_backend import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RoomStayCandidates:
    room_stay_candidate: List[RoomStayCandidate] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('RoomStayCandidate') }})
    

