"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ShareWithEnum(str, Enum):
    r"""Share with like Supplier,agency etc"""
    SUPPLIER = 'Supplier'
    AGENCY = 'Agency'
    TRAVELER = 'Traveler'
