"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TextFormatEnum(str, Enum):
    r"""Describes the format of text such as plain text or html"""
    PLAIN_TEXT = 'PlainText'
    HTML = 'HTML'
