"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TourCodeTypeEnum(str, Enum):
    BULK_TOUR = 'Bulk Tour'
    INCLUSIVE_TOUR = 'Inclusive Tour'
