"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class UnitOfSize(str, Enum):
    r"""List of units of size i.e Square Feet, Square Meters"""
    SQUARE_FEET = 'Square Feet'
    SQUARE_METERS = 'Square Meters'
