"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class UnitOfMeasureEnum(str, Enum):
    r"""The unit of measure in a code format. Refer to OpenTravel Code List Unit of Measure Code (UOM)."""
    MILES = 'Miles'
    KILOMETERS = 'Kilometers'
    METERS = 'Meters'
    MILLIMETERS = 'Millimeters'
    CENTIMETERS = 'Centimeters'
    YARDS = 'Yards'
    FEET = 'Feet'
    INCHES = 'Inches'
    PIXELS = 'Pixels'
    BLOCK = 'Block'
    MEGABYTES = 'Megabytes'
    GIGABYTES = 'Gigabytes'
    SQUARE_FEET = 'Square feet'
    SQUARE_METERS = 'Square meters'
    POUNDS = 'Pounds'
    KILOGRAMS = 'Kilograms'
    SQUARE_INCH = 'Square inch'
    SQUARE_YARD = 'Square yard'
    ACRE = 'Acre'
    SQUARE_MILLIMETER = 'Square millimeter'
    SQUARE_CENTIMETER = 'Square centimeter'
    HECTARE = 'Hectare'
    OUNCE = 'Ounce'
    GRAM = 'Gram'
    GALLONS = 'Gallons'
    LITERS = 'Liters'
    KILOWATTS = 'Kilowatts'
    CUBIC_METERS = 'Cubic meters'
