"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class YesNoUnknownEnum(str, Enum):
    r"""Yes , No , Unknown"""
    YES = 'Yes'
    NO = 'No'
    UNKNOWN = 'Unknown'
