"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class YesNoInheritEnum(str, Enum):
    r"""Used to indicate marketing preferences, Yes, No, Inherit"""
    YES = 'Yes'
    NO = 'No'
    INHERIT = 'Inherit'
