"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from .hotel_availability import HotelAvailability
from .hotel_rules import HotelRules
from .precision_search_hotel import PrecisionSearchHotel
from .reservation_hotel import ReservationHotel
from .sdkconfiguration import SDKConfiguration
from .search_hotel import SearchHotel
from akaris_backend import utils
from akaris_backend.models import shared

class AkarisBackend:
    hotel_availability: HotelAvailability
    hotel_rules: HotelRules
    precision_search_hotel: PrecisionSearchHotel
    reservation_hotel: ReservationHotel
    search_hotel: SearchHotel

    sdk_configuration: SDKConfiguration

    def __init__(self,
                 o_auth2: str,
                 server_idx: int = None,
                 server_url: str = None,
                 url_params: dict[str, str] = None,
                 client: requests_http.Session = None,
                 retry_config: utils.RetryConfig = None
                 ) -> None:
        """Instantiates the SDK configuring it with the provided parameters.
        
        :param o_auth2: The o_auth2 required for authentication
        :type o_auth2: str
        :param server_idx: The index of the server to use for all operations
        :type server_idx: int
        :param server_url: The server URL to use for all operations
        :type server_url: str
        :param url_params: Parameters to optionally template the server URL with
        :type url_params: dict[str, str]
        :param client: The requests.Session HTTP client to use for all operations
        :type client: requests_http.Session
        :param retry_config: The utils.RetryConfig to use globally
        :type retry_config: utils.RetryConfig
        """
        if client is None:
            client = requests_http.Session()
        
        
        security_client = utils.configure_security_client(client, security)
        
        
        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        self.sdk_configuration = SDKConfiguration(client, security_client, server_url, server_idx, retry_config=retry_config)
       
        self._init_sdks()
    
    def _init_sdks(self):
        self.hotel_availability = HotelAvailability(self.sdk_configuration)
        self.hotel_rules = HotelRules(self.sdk_configuration)
        self.precision_search_hotel = PrecisionSearchHotel(self.sdk_configuration)
        self.reservation_hotel = ReservationHotel(self.sdk_configuration)
        self.search_hotel = SearchHotel(self.sdk_configuration)
    